retargeting:
  type: DexPilot
  urdf_path: gx10/urdf/gx10.urdf


  # Target refers to the retargeting target, which is the robot hand
  wrist_link_name: "base_link"
  finger_tip_link_names: [ "Link11", "Link12", "Link13"]
  scaling_factor: 1.05

  # A smaller alpha means stronger filtering, i.e. more smooth but also larger latency
  low_pass_alpha: 1


